apiVersion: v1
kind: Service
metadata:
  name: kushmanda-service
spec:
  selector:
    app: kushmanda
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer
